vich_uploader:
  db_driver: orm

  mappings:
    dish_image:
      uri_prefix: /uploads/dishes
      upload_destination: "%kernel.project_dir%/public/uploads/dishes"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      delete_on_update: true
      delete_on_remove: true

    order_documents:
      uri_prefix: /uploads/orders
      upload_destination: "%kernel.project_dir%/public/uploads/orders"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      delete_on_update: true
      delete_on_remove: true
